/*! Generated by redux-scfld */
'use strict';

import {
    STATUS_SUCCESS,
} from './../../types';

import defaultState from '../../states/message';

import {showMessage} from '../../pure/message-functions';

export default function(state = defaultState, action) {
    switch(action.status) {
        case STATUS_SUCCESS:
            return showMessage(state, action.result);
    }
    return state;
};