/*! Generated by redux-scfld */
'use strict';

import {
    PROGRESS,
    SUCCESS,
    FAILURE,
} from './../../types';
import {setPost} from '../../pure/post-functions'

export default function(state, action) {
    switch(action.status) {
        case PROGRESS:
            break;
        case SUCCESS:
            return setPost(action.result);
        case FAILURE:
            break;
    }
    return state;
};