/*! Generated by redux-scfld */
'use strict';

import {
    STATUS_PROCESS,
    STATUS_SUCCESS,
    STATUS_FAILURE,
} from './../../types';

import {setPosts} from '../../pure/posts-functions'

import defaultState from '../../states/posts';

export default function(state = defaultState, action) {
    switch(action.status) {
        case STATUS_PROCESS:
            return state;
        case STATUS_SUCCESS:
            return setPosts(state, action.result);
        case STATUS_FAILURE:
            return defaultState.set('error', { error: action.error });
    }
    return state;
};