/*! Generated by redux-scfld */
'use strict';


import {
    STATUS_PROCESS,
    STATUS_SUCCESS,
    STATUS_FAILURE
} from './../../types';

import defaultState from './../../states/posts.js';

export default function(state = defaultState, action) {
    switch(action.status) {
        case STATUS_SUCCESS:
            return defaultState;
    }
    return state;
};