/*! Generated by redux-scfld */
'use strict';

import xhr from 'xhr';

class RequestError extends Error {
    constructor(message, code) {
        super(message);
        this.code = code;
    }
}

export default function request(url) {
    return new Promise( (resolve, reject) => {
        xhr({url}, function (err, resp, body) {
            if (err) {
                return reject(new RequestError(err.message, 400));
            }
            if ( parseInt(resp.statusCode/100) !== 2) {
                return reject(new RequestError(body, resp.statusCode));
            }
            try {
                resolve(JSON.parse(body))
            } catch (e) {
                reject(new RequestError(e.message, 400));
            }
        });
    }) ;
}