/*! Generated by redux-scfld */
'use strict';

import xhr from 'xhr';

export default function request(url) {
    return new Promise( (resolve, reject) => {
        xhr({url}, function (err, resp, body) {
            if (err) {
                return reject(err)
            }
            if ( parseInt(resp.statusCode/100) !== 2) {
                return reject(new Error(body));
            }
            try {
                resolve(JSON.parse(body))
            } catch (e) {
                reject(e);
            }
        });
    }) ;
}