/*! Generated by redux-scfld */
'use strict';


import {
    STATUS_SUCCESS,
} from './../../types';

import defaultState from './../../states/error';
import {setError} from '../../pure/error-functions';

export default function(state = defaultState, action) {
    switch(action.status) {
        case STATUS_SUCCESS:
            return setError(state, action.result);
    }
    return state;
};