/*! Generated by redux-scfld not for editing */
'use strict';

import { Map } from 'immutable';
import error from './error';
import message from './message';
import post from './post';
import posts from './posts';

export default Map({
    error,
    message,
    post,
    posts
});
