/*! Generated by redux-scfld not for editing */
'use strict';


// Statuses
export const STATUS_PROCESS = 'STATUS_PROCESS';
export const STATUS_SUCCESS = 'STATUS_SUCCESS';
export const STATUS_FAILURE = 'STATUS_FAILURE';

// Generated Namespaces
export const NAMESPACE_ERROR = 'error';
export const NAMESPACE_MESSAGE = 'message';
export const NAMESPACE_POST = 'post';
export const NAMESPACE_POSTS = 'posts';

export const NAMESPACES = [
    NAMESPACE_ERROR,
    NAMESPACE_MESSAGE,
    NAMESPACE_POST,
    NAMESPACE_POSTS
];
// Generated Types
export const ERROR_RAISE = 'ERROR_RAISE';
export const ERROR_RESET = 'ERROR_RESET';
export const MESSAGE_HIDE = 'MESSAGE_HIDE';
export const MESSAGE_SHOW = 'MESSAGE_SHOW';
export const POST_FETCH = 'POST_FETCH';
export const POST_RESET = 'POST_RESET';
export const POSTS_FETCH = 'POSTS_FETCH';
export const POSTS_RESET = 'POSTS_RESET';