/*! Generated by redux-scfld not for editing */
'use strict';

export const PROGRESS = 'PROGRESS';
export const SUCCESS = 'SUCCESS';
export const FAILURE = 'FAILURE';

export const NAMESPACE = {

    post: 'post',

    posts: 'posts',

};


export const POST_FETCH = 'POST_FETCH';

export const POSTS_FETCH = 'POSTS_FETCH';

